name: commerce
description: "E-Commerce Application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  http: ^1.2.1
  get: ^4.6.6
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.6
  lottie: ^3.1.2
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  sqflite: ^2.3.3+1
  path: ^1.9.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/icons/
     - assets/svg/
     - assets/
     - assets/lottie/
